# Generated by Django 3.1.4 on 2021-05-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='publisher_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
